#+TITLE: ox-jira
#+AUTHOR: Stig Brautaset
#+PROPERTY: header-args:emacs-lisp :tangle yes
* ox-jira - a JIRA export backend for Org mode

** Header

   First come some [[http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][conventional headers]] that libraries tend to include. Cask
   _requires_ them, so I assume they are a good idea.

*** Short description

    #+BEGIN_SRC emacs-lisp
      ;;; ox-jira.el --- an Org mode export backend for JIRA format
    #+END_SRC

*** Copyright & License

    I prefer the MIT license because it is short enough to read without toilet
    or tea breaks, and I _think_ I can actually wrap my head around it. (And I
    feel it's important to understand the license of your choice.)

    #+BEGIN_SRC emacs-lisp
      ;;; Copyright (C) 2016 Stig Brautaset

      ;; Permission is hereby granted, free of charge, to any person obtaining a
      ;; copy of this software and associated documentation files (the "Software"),
      ;; to deal in the Software without restriction, including without limitation
      ;; the rights to use, copy, modify, merge, publish, distribute, sublicense,
      ;; and/or sell copies of the Software, and to permit persons to whom the
      ;; Software is furnished to do so, subject to the following conditions:

      ;; The above copyright notice and this permission notice shall be included in
      ;; all copies or substantial portions of the Software.

      ;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      ;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      ;; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
      ;; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
      ;; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
      ;; FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
      ;; DEALINGS IN THE SOFTWARE.
    #+END_SRC

*** Author

    #+BEGIN_SRC emacs-lisp
      ;;; Author: Stig Brautaset <stig@brautaset.org>
    #+END_SRC

*** Keywords

    Define the keywords that can be used to find this package with
    =finder-by-keyword= (=C-h p=).

    #+BEGIN_SRC emacs-lisp
      ;; Keywords: outlines, hypermedia, wp
    #+END_SRC
*** Distribution

    #+BEGIN_SRC emacs-lisp
      ;; This file is NOT part of GNU Emacs.
    #+END_SRC
*** Version

    #+BEGIN_SRC emacs-lisp
      ;;; Version: 0.1-SNAPSHOT
    #+END_SRC

*** Homepage

    #+BEGIN_SRC emacs-lisp
      ;; Homepage: https://github.com/stig/ox-jira.el
    #+END_SRC

*** Package Requires

    We requires Org version 8 or above, as the export backend system we use
    was introduced then.

    #+BEGIN_SRC emacs-lisp
      ;; Package-Requires: ((org "8.0"))
    #+END_SRC

** Code

   First a special header to denote that we're done with the header section
   and starting the actual code now.

   #+BEGIN_SRC emacs-lisp
     ;;; Code:
   #+END_SRC

** Footer

   Now we need to put and end to this malarky. There's a magic comment for
   that too. It looks like this:

   #+BEGIN_SRC emacs-lisp
     ;;; ox-jira.el ends here
   #+END_SRC
