#+TITLE: JIRA Backend for Org Export Engine
#+AUTHOR: Stig Brautaset
* Introduction

  This module plugs into the regular Org Export Engine and transforms Org
  files to JIRA markup for pasting into JIRA tickets & comments.

  My last three jobs I've had to use JIRA, and had to deal with its (to me)
  incredibly unintuitive markup format. Having discovered---and fallen in
  love with---Org mode I now find myself writing everything in Org and
  exporting to various other formats (html, markdown, plain text) but I
  haven't been able to find a way to export to JIRA. So I am attempting to
  write one, and learn about Emacs package development at the same time.

* Usage

  Currently this is not on Melpa, though I'll see about that once it does what
  I want. For now you can clone this repo and do one of:

  #+BEGIN_EXAMPLE
  M-x org-babel-load-file RET ox-jira.org RET
  #+END_EXAMPLE

  Or:

  #+BEGIN_EXAMPLE
  M-x load-file RET ox-jira.el RET
  #+END_EXAMPLE

* Maturity

  Very immature. Positively juvenile. Please don't laugh.

  Saying that, it now does pretty much everything I need it to. YMMV :-)

* License

  Copyright (C) 2016 Stig Brautaset

  This program is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the Free
  Software Foundation, either version 3 of the License, or (at your option)
  any later version.

  This program is distributed in the hope that it will be useful, but WITHOUT
  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
  more details.

  You should have received a copy of the GNU General Public License along with
  this program. If not, see <http://www.gnu.org/licenses/>.

* Contributing

  I'm happy to consider contributions. Since this is my first attempt at an
  Emacs package I've bound to have made lots of mistakes. Help me correct
  them, and keep the pull requests coming!

  Code contributions have _a lot_ better chance of being merged if they come
  with tests. However, code contributions are not everything. Opening an issue
  with a reproducible test case, like "I expected this but got this" is also a
  valuable contribution.

  The source and tests both lives in =.org= files and is "tangled" into
  corresponding =.el= files. Running the =./run-tests.sh= script automatically
  takes care of that process. You'll need [[https://cask.github.io][Cask]] installed to run this script.
